### PR TITLE
removed default net creation

### PR DESCRIPTION
**Pull request by Waterhouse-GFT**
## PR Type  
What kind of change does this PR introduce?  
  
Please check the boxes that applies to this PR.  
  
- [ ] Bugfix  
- [ ] Feature  
- [ ] Code style update (formatting, local variables)  
- [x] Refactoring (no functional changes, no api changes)  
- [ ] Build related changes  
- [ ] CI related changes  
- [ ] Documentation content changes  
- [ ] TranquilityBase application / infrastructure changes  
- [ ] Other... Please describe:  

## Purpose 
Describe the problem or feature with a **link** to the issues.    
Also please describe which sections of the code do what and for what reason.  
 
Removed the default firewall rule deletion commands from tb-config-creator, which will be replaced with org policy skip default network creation rule. 

image

Needs to be merged at the same time as the policy is enabled to avoid disrupting deployments.
## Reviewers  
 - **Reviewer A** please review this part.  
 - **Review B** please review this part.  
  
  ## Checklist  
 - [x] This PR is linked to one or more issues.  
 - [x] This PR has been tested (attach evidence if possible).  
 - [ ] This PR has passed style guidelines.

### CODE REVIEW

**Review by rjmco — CHANGES_REQUESTED** [review]
I think this will lead to a chicken and egg problem. What action comes first?
- Overriding the default value for `constraints/compute.skipDefaultNetworkCreation` org policy on the organization node or the TB root folder
- Creating the `bootstrap-<random>` project?

I don't see on this script (`tb-config-creator`) an action an instruction to change the org policy and therefore I can't answer the question above. Can you clarify?

If it's not possible to answer the question, then the safest approach would be check if the default network exists and if so, delete the firewall rules and the default network.

**Comment by Waterhouse-GFT** [comment]
> I don't see on this script (`tb-config-creator`) an action an instruction to change the org policy and therefore I can't answer the question above. Can you clarify?
> 
> If it's not possible to answer the question, then the safest approach would be check if the default network exists and if so, delete the firewall rules and the default network.

I don't think that the aim is to enable any org policies in config creator, it was to test whether the deploy would be successfull if an org policy was enabled at the org or folder level. The idea being that projects outside of tb would not be able to automatically create a network, while not interfering with tb deployments.

**Comment by rjmco** [comment]
> > I don't see on this script (`tb-config-creator`) an action an instruction to change the org policy and therefore I can't answer the question above. Can you clarify?
> > If it's not possible to answer the question, then the safest approach would be check if the default network exists and if so, delete the firewall rules and the default network.
> 
> I don't think that the aim is to enable any org policies in config creator, it was to test whether the deploy would be successfull if an org policy was enabled at the org or folder level. The idea being that projects outside of tb would not be able to automatically create a network, while not interfering with tb deployments.

If it was just a test, then we can close this PR without merging. On the other hand, if the goal is to be able to deploy `tb-gcp` on an organization regardless of whether it has `constraints/compute.skipDefaultNetworkCreation` org policy enforced, then we shouldn't just delete code, we should instead check if the `default` network exists and if so remove it.

One side note, `constraints/compute.skipDefaultNetworkCreation` organization policy does not prevent users from creating  [auto mode VPC networks](https://cloud.google.com/vpc/docs/vpc#subnet-ranges) at will, it just stops Compute Engine from creating one automatically as soon as it's API (`compute.googleapis.com`) is enabled.

**Comment by rjmco** [comment]
Works when `constraints/compute.skipDefaultNetworkCreation` is not enforced as shown below:
```
Essential APIs activated.
Checking if the default VPC network was created on compute.googleapis.com activation...
The default VPC network was created. Deleting it as per best practices...
Deleted [https://www.googleapis.com/compute/v1/projects/bootstrap-<obfuscated>/global/firewalls/default-allow-icmp].
Deleted [https://www.googleapis.com/compute/v1/projects/bootstrap-<obfuscated>/global/firewalls/default-allow-rdp].
Deleted [https://www.googleapis.com/compute/v1/projects/bootstrap-<obfuscated>/global/firewalls/default-allow-ssh].
Deleted [https://www.googleapis.com/compute/v1/projects/bootstrap-<obfuscated>/global/firewalls/default-allow-internal].
Deleted [https://www.googleapis.com/compute/v1/projects/bootstrap-<obfuscated>/global/networks/default].
Finished deleting the default VPC network.

Configuration completed!
```
and when `constraints/compute.skipDefaultNetworkCreation` is enforced as shown below:
```
Essential APIs activated.
Checking if the default VPC network was created on compute.googleapis.com activation...
The default VPC network was not created.
Configuration completed!
```

**Review by rjmco — APPROVED** [review]
LGTM

**Pull request merged**
